name = "know-weather-assistant"
main = "src/index.js"
compatibility_date = "2026-07-24"

[vars]
ALLOWED_ORIGIN = "https://manishh28.github.io"
AI_MODEL = "@cf/meta/llama-3.1-8b-instruct-fast"

[ai]
binding = "AI"
